import { Country } from './types';

export const countries: Country[] = [
  { name: 'Afghanistan', flag: '🇦🇫', code: 'AF', dial_code: '+93', pattern: '... ... ...' },
  { name: 'Albania', flag: '🇦🇱', code: 'AL', dial_code: '+355', pattern: '... ... ...' },
  { name: 'Algeria', flag: '🇩🇿', code: 'DZ', dial_code: '+213', pattern: '... .. .. ..' },
  { name: 'American Samoa', flag: '🇦🇸', code: 'AS', dial_code: '+1684', pattern: '(...) ...-....' },
  { name: 'Andorra', flag: '🇦🇩', code: 'AD', dial_code: '+376', pattern: '... ...' },
  { name: 'Angola', flag: '🇦🇴', code: 'AO', dial_code: '+244', pattern: '... ... ...' },
  { name: 'Anguilla', flag: '🇦🇮', code: 'AI', dial_code: '+1264', pattern: '(...) ...-....' },
  { name: 'Antigua and Barbuda', flag: '🇦🇬', code: 'AG', dial_code: '+1268', pattern: '(...) ...-....' },
  { name: 'Argentina', flag: '🇦🇷', code: 'AR', dial_code: '+54', pattern: '... ...-....' },
  { name: 'Armenia', flag: '🇦🇲', code: 'AM', dial_code: '+374', pattern: '.. ...-...' },
  { name: 'Aruba', flag: '🇦🇼', code: 'AW', dial_code: '+297', pattern: '...-....' },
  { name: 'Australia', flag: '🇦🇺', code: 'AU', dial_code: '+61', pattern: '... ... ...' },
  { name: 'Austria', flag: '🇦🇹', code: 'AT', dial_code: '+43', pattern: '... ...-....' },
  { name: 'Azerbaijan', flag: '🇦🇿', code: 'AZ', dial_code: '+994', pattern: '.. ... .. ..' },
  { name: 'Bahamas', flag: '🇧🇸', code: 'BS', dial_code: '+1242', pattern: '(...) ...-....' },
  { name: 'Bahrain', flag: '🇧🇭', code: 'BH', dial_code: '+973', pattern: '.... ....' },
  { name: 'Bangladesh', flag: '🇧🇩', code: 'BD', dial_code: '+880', pattern: '....-......' },
  { name: 'Barbados', flag: '🇧🇧', code: 'BB', dial_code: '+1246', pattern: '(...) ...-....' },
  { name: 'Belarus', flag: '🇧🇾', code: 'BY', dial_code: '+375', pattern: '(..) ...-..-..' },
  { name: 'Belgium', flag: '🇧🇪', code: 'BE', dial_code: '+32', pattern: '... .. .. ..' },
  { name: 'Belize', flag: '🇧🇿', code: 'BZ', dial_code: '+501', pattern: '...-....' },
  { name: 'Benin', flag: '🇧🇯', code: 'BJ', dial_code: '+229', pattern: '.. .. .. ..' },
  { name: 'Bermuda', flag: '🇧🇲', code: 'BM', dial_code: '+1441', pattern: '(...) ...-....' },
  { name: 'Bhutan', flag: '🇧🇹', code: 'BT', dial_code: '+975', pattern: '.. .. .. ..' },
  { name: 'Bolivia', flag: '🇧🇴', code: 'BO', dial_code: '+591', pattern: '... .....' },
  { name: 'Bosnia and Herzegovina', flag: '🇧🇦', code: 'BA', dial_code: '+387', pattern: '.. ...-...' },
  { name: 'Botswana', flag: '🇧🇼', code: 'BW', dial_code: '+267', pattern: '.. ... ...' },
  { name: 'Brazil', flag: '🇧🇷', code: 'BR', dial_code: '+55', pattern: '(..) .....-....' },
  { name: 'British Virgin Islands', flag: '🇻🇬', code: 'VG', dial_code: '+1284', pattern: '(...) ...-....' },
  { name: 'Brunei', flag: '🇧🇳', code: 'BN', dial_code: '+673', pattern: '...-....' },
  { name: 'Bulgaria', flag: '🇧🇬', code: 'BG', dial_code: '+359', pattern: '... ... ...' },
  { name: 'Burkina Faso', flag: '🇧🇫', code: 'BF', dial_code: '+226', pattern: '.. .. .. ..' },
  { name: 'Burundi', flag: '🇧🇮', code: 'BI', dial_code: '+257', pattern: '.. .. .. ..' },
  { name: 'Cambodia', flag: '🇰🇭', code: 'KH', dial_code: '+855', pattern: '.. ... ...' },
  { name: 'Cameroon', flag: '🇨🇲', code: 'CM', dial_code: '+237', pattern: '.... ....' },
  { name: 'Canada', flag: '🇨🇦', code: 'CA', dial_code: '+1', pattern: '(...) ...-....' },
  { name: 'Cape Verde', flag: '🇨🇻', code: 'CV', dial_code: '+238', pattern: '... .. ..' },
  { name: 'Cayman Islands', flag: '🇰🇾', code: 'KY', dial_code: '+1345', pattern: '(...) ...-....' },
  { name: 'Central African Republic', flag: '🇨🇫', code: 'CF', dial_code: '+236', pattern: '.. .. .. ..' },
  { name: 'Chad', flag: '🇹🇩', code: 'TD', dial_code: '+235', pattern: '.. .. .. ..' },
  { name: 'Chile', flag: '🇨🇱', code: 'CL', dial_code: '+56', pattern: '.. .... ....' },
  { name: 'China', flag: '🇨🇳', code: 'CN', dial_code: '+86', pattern: '...-....-....' },
  { name: 'Colombia', flag: '🇨🇴', code: 'CO', dial_code: '+57', pattern: '... ...-....' },
  { name: 'Congo (DRC)', flag: '🇨🇩', code: 'CD', dial_code: '+243', pattern: '... ... ...' },
  { name: 'Congo (Republic)', flag: '🇨🇬', code: 'CG', dial_code: '+242', pattern: '.. ... ....' },
  { name: 'Cook Islands', flag: '🇨🇰', code: 'CK', dial_code: '+682', pattern: '..-...' },
  { name: 'Costa Rica', flag: '🇨🇷', code: 'CR', dial_code: '+506', pattern: '....-....' },
  { name: 'Croatia', flag: '🇭🇷', code: 'HR', dial_code: '+385', pattern: '.. ...-....' },
  { name: 'Cuba', flag: '🇨🇺', code: 'CU', dial_code: '+53', pattern: '.. ...-....' },
  { name: 'Cyprus', flag: '🇨🇾', code: 'CY', dial_code: '+357', pattern: '.. ...-...' },
  { name: 'Czech Republic', flag: '🇨🇿', code: 'CZ', dial_code: '+420', pattern: '... ... ...' },
  { name: 'Denmark', flag: '🇩🇰', code: 'DK', dial_code: '+45', pattern: '.. .. .. ..' },
  { name: 'Djibouti', flag: '🇩🇯', code: 'DJ', dial_code: '+253', pattern: '.. .. .. ..' },
  { name: 'Dominica', flag: '🇩🇲', code: 'DM', dial_code: '+1767', pattern: '(...) ...-....' },
  { name: 'Dominican Republic', flag: '🇩🇴', code: 'DO', dial_code: '+1', pattern: '(...) ...-....' },
  { name: 'Ecuador', flag: '🇪🇨', code: 'EC', dial_code: '+593', pattern: '.. ...-....' },
  { name: 'Egypt', flag: '🇪🇬', code: 'EG', dial_code: '+20', pattern: '... ...-....' },
  { name: 'El Salvador', flag: '🇸🇻', code: 'SV', dial_code: '+503', pattern: '....-....' },
  { name: 'Estonia', flag: '🇪🇪', code: 'EE', dial_code: '+372', pattern: '....-....' },
  { name: 'Ethiopia', flag: '🇪🇹', code: 'ET', dial_code: '+251', pattern: '.. ...-....' },
  { name: 'Faroe Islands', flag: '🇫🇴', code: 'FO', dial_code: '+298', pattern: '......' },
  { name: 'Fiji', flag: '🇫🇯', code: 'FJ', dial_code: '+679', pattern: '...-....' },
  { name: 'Finland', flag: '🇫🇮', code: 'FI', dial_code: '+358', pattern: '.. ... .. ..' },
  { name: 'France', flag: '🇫🇷', code: 'FR', dial_code: '+33', pattern: '.. .. .. .. ..' },
  { name: 'French Guiana', flag: '🇬🇫', code: 'GF', dial_code: '+594', pattern: '.....-....' },
  { name: 'French Polynesia', flag: '🇵🇫', code: 'PF', dial_code: '+689', pattern: '.. .. ..' },
  { name: 'Gabon', flag: '🇬🇦', code: 'GA', dial_code: '+241', pattern: '.. .. .. ..' },
  { name: 'Gambia', flag: '🇬🇲', code: 'GM', dial_code: '+220', pattern: '...-....' },
  { name: 'Georgia', flag: '🇬🇪', code: 'GE', dial_code: '+995', pattern: '... .. .. ..' },
  { name: 'Germany', flag: '🇩🇪', code: 'DE', dial_code: '+49', pattern: '....-.......' },
  { name: 'Ghana', flag: '🇬🇭', code: 'GH', dial_code: '+233', pattern: '.. ...-....' },
  { name: 'Gibraltar', flag: '🇬🇮', code: 'GI', dial_code: '+350', pattern: '...-.....' },
  { name: 'Greece', flag: '🇬🇷', code: 'GR', dial_code: '+30', pattern: '... ...-....' },
  { name: 'Greenland', flag: '🇬🇱', code: 'GL', dial_code: '+299', pattern: '.. .. ..' },
  { name: 'Grenada', flag: '🇬🇩', code: 'GD', dial_code: '+1473', pattern: '(...) ...-....' },
  { name: 'Guadeloupe', flag: '🇬🇵', code: 'GP', dial_code: '+590', pattern: '.....-....' },
  { name: 'Guam', flag: '🇬🇺', code: 'GU', dial_code: '+1671', pattern: '(...) ...-....' },
  { name: 'Guatemala', flag: '🇬🇹', code: 'GT', dial_code: '+502', pattern: '....-....' },
  { name: 'Guinea', flag: '🇬🇳', code: 'GN', dial_code: '+224', pattern: '... .. .. ..' },
  { name: 'Guyana', flag: '🇬🇾', code: 'GY', dial_code: '+592', pattern: '...-....' },
  { name: 'Haiti', flag: '🇭🇹', code: 'HT', dial_code: '+509', pattern: '.. .. .. ..' },
  { name: 'Honduras', flag: '🇭🇳', code: 'HN', dial_code: '+504', pattern: '....-....' },
  { name: 'Hong Kong', flag: '🇭🇰', code: 'HK', dial_code: '+852', pattern: '.... ....' },
  { name: 'Hungary', flag: '🇭🇺', code: 'HU', dial_code: '+36', pattern: '.. ...-....' },
  { name: 'Iceland', flag: '🇮🇸', code: 'IS', dial_code: '+354', pattern: '...-....' },
  { name: 'India', flag: '🇮🇳', code: 'IN', dial_code: '+91', pattern: '.....-.....' },
  { name: 'Indonesia', flag: '🇮🇩', code: 'ID', dial_code: '+62', pattern: '...-....-....' },
  { name: 'Iran', flag: '🇮🇷', code: 'IR', dial_code: '+98', pattern: '... ...-....' },
  { name: 'Iraq', flag: '🇮🇶', code: 'IQ', dial_code: '+964', pattern: '... ...-....' },
  { name: 'Ireland', flag: '🇮🇪', code: 'IE', dial_code: '+353', pattern: '.. ...-....' },
  { name: 'Israel', flag: '🇮🇱', code: 'IL', dial_code: '+972', pattern: '..-....-....' },
  { name: 'Italy', flag: '🇮🇹', code: 'IT', dial_code: '+39', pattern: '... ....-....' },
  { name: 'Jamaica', flag: '🇯🇲', code: 'JM', dial_code: '+1876', pattern: '(...) ...-....' },
  { name: 'Japan', flag: '🇯🇵', code: 'JP', dial_code: '+81', pattern: '..-....-....' },
  { name: 'Jordan', flag: '🇯🇴', code: 'JO', dial_code: '+962', pattern: '....-....' },
  { name: 'Kazakhstan', flag: '🇰🇿', code: 'KZ', dial_code: '+7', pattern: '(...) ...-..-..' },
  { name: 'Kenya', flag: '🇰🇪', code: 'KE', dial_code: '+254', pattern: '...-......' },
  { name: 'Kuwait', flag: '🇰🇼', code: 'KW', dial_code: '+965', pattern: '....-....' },
  { name: 'Kyrgyzstan', flag: '🇰🇬', code: 'KG', dial_code: '+996', pattern: '... ...-...' },
  { name: 'Laos', flag: '🇱🇦', code: 'LA', dial_code: '+856', pattern: '.. .. ... ...' },
  { name: 'Latvia', flag: '🇱🇻', code: 'LV', dial_code: '+371', pattern: '.. ... ...' },
  { name: 'Lebanon', flag: '🇱🇧', code: 'LB', dial_code: '+961', pattern: '.. ...-...' },
  { name: 'Lesotho', flag: '🇱🇸', code: 'LS', dial_code: '+266', pattern: '....-....' },
  { name: 'Liberia', flag: '🇱🇷', code: 'LR', dial_code: '+231', pattern: '.. ...-....' },
  { name: 'Libya', flag: '🇱🇾', code: 'LY', dial_code: '+218', pattern: '..-.......' },
  { name: 'Liechtenstein', flag: '🇱🇮', code: 'LI', dial_code: '+423', pattern: '... ... ...' },
  { name: 'Lithuania', flag: '🇱🇹', code: 'LT', dial_code: '+370', pattern: '... .. ...' },
  { name: 'Luxembourg', flag: '🇱🇺', code: 'LU', dial_code: '+352', pattern: '... ... ...' },
  { name: 'Macau', flag: '🇲🇴', code: 'MO', dial_code: '+853', pattern: '....-....' },
  { name: 'Madagascar', flag: '🇲🇬', code: 'MG', dial_code: '+261', pattern: '.. .. ... ..' },
  { name: 'Malaysia', flag: '🇲🇾', code: 'MY', dial_code: '+60', pattern: '..-....-....' },
  { name: 'Maldives', flag: '🇲🇻', code: 'MV', dial_code: '+960', pattern: '...-....' },
  { name: 'Mali', flag: '🇲🇱', code: 'ML', dial_code: '+223', pattern: '.. .. .. ..' },
  { name: 'Malta', flag: '🇲🇹', code: 'MT', dial_code: '+356', pattern: '....-....' },
  { name: 'Martinique', flag: '🇲🇶', code: 'MQ', dial_code: '+596', pattern: '.....-....' },
  { name: 'Mauritania', flag: '🇲🇷', code: 'MR', dial_code: '+222', pattern: '.. .. .. ..' },
  { name: 'Mauritius', flag: '🇲🇺', code: 'MU', dial_code: '+230', pattern: '...-....' },
  { name: 'Mexico', flag: '🇲🇽', code: 'MX', dial_code: '+52', pattern: '... ...-....' },
  { name: 'Moldova', flag: '🇲🇩', code: 'MD', dial_code: '+373', pattern: '....-....' },
  { name: 'Monaco', flag: '🇲🇨', code: 'MC', dial_code: '+377', pattern: '... ... ...' },
  { name: 'Mongolia', flag: '🇲🇳', code: 'MN', dial_code: '+976', pattern: '....-....' },
  { name: 'Montenegro', flag: '🇲🇪', code: 'ME', dial_code: '+382', pattern: '.. ...-...' },
  { name: 'Montserrat', flag: '🇲🇸', code: 'MS', dial_code: '+1664', pattern: '(...) ...-....' },
  { name: 'Morocco', flag: '🇲🇦', code: 'MA', dial_code: '+212', pattern: '..-....-....' },
  { name: 'Mozambique', flag: '🇲🇿', code: 'MZ', dial_code: '+258', pattern: '.. ...-....' },
  { name: 'Myanmar', flag: '🇲🇲', code: 'MM', dial_code: '+95', pattern: '.. ... ...' },
  { name: 'Namibia', flag: '🇳🇦', code: 'NA', dial_code: '+264', pattern: '.. ...-....' },
  { name: 'Nepal', flag: '🇳🇵', code: 'NP', dial_code: '+977', pattern: '...-.......' },
  { name: 'Netherlands', flag: '🇳🇱', code: 'NL', dial_code: '+31', pattern: '.. ........' },
  { name: 'New Caledonia', flag: '🇳🇨', code: 'NC', dial_code: '+687', pattern: '..-....' },
  { name: 'New Zealand', flag: '🇳🇿', code: 'NZ', dial_code: '+64', pattern: '... ...-....' },
  { name: 'Nicaragua', flag: '🇳🇮', code: 'NI', dial_code: '+505', pattern: '....-....' },
  { name: 'Niger', flag: '🇳🇪', code: 'NE', dial_code: '+227', pattern: '.. .. .. ..' },
  { name: 'Nigeria', flag: '🇳🇬', code: 'NG', dial_code: '+234', pattern: '... ... ....' },
  { name: 'North Macedonia', flag: '🇲🇰', code: 'MK', dial_code: '+389', pattern: '.. ...-...' },
  { name: 'Norway', flag: '🇳🇴', code: 'NO', dial_code: '+47', pattern: '... .. ...' },
  { name: 'Oman', flag: '🇴🇲', code: 'OM', dial_code: '+968', pattern: '....-....' },
  { name: 'Pakistan', flag: '🇵🇰', code: 'PK', dial_code: '+92', pattern: '...-.......' },
  { name: 'Palau', flag: '🇵🇼', code: 'PW', dial_code: '+680', pattern: '...-....' },
  { name: 'Panama', flag: '🇵🇦', code: 'PA', dial_code: '+507', pattern: '...-....' },
  { name: 'Papua New Guinea', flag: '🇵🇬', code: 'PG', dial_code: '+675', pattern: '...-....' },
  { name: 'Paraguay', flag: '🇵🇾', code: 'PY', dial_code: '+595', pattern: '... ...-...' },
  { name: 'Peru', flag: '🇵🇪', code: 'PE', dial_code: '+51', pattern: '... ... ...' },
  { name: 'Philippines', flag: '🇵🇭', code: 'PH', dial_code: '+63', pattern: '...-....-....' },
  { name: 'Poland', flag: '🇵🇱', code: 'PL', dial_code: '+48', pattern: '...-...-...' },
  { name: 'Portugal', flag: '🇵🇹', code: 'PT', dial_code: '+351', pattern: '... ... ...' },
  { name: 'Puerto Rico', flag: '🇵🇷', code: 'PR', dial_code: '+1', pattern: '(...) ...-....' },
  { name: 'Qatar', flag: '🇶🇦', code: 'QA', dial_code: '+974', pattern: '....-....' },
  { name: 'Romania', flag: '🇷🇴', code: 'RO', dial_code: '+40', pattern: '... ... ...' },
  { name: 'Russia', flag: '🇷🇺', code: 'RU', dial_code: '+7', pattern: '(...) ...-..-..' },
  { name: 'Rwanda', flag: '🇷🇼', code: 'RW', dial_code: '+250', pattern: '... ... ...' },
  { name: 'Samoa', flag: '🇼🇸', code: 'WS', dial_code: '+685', pattern: '..-....' },
  { name: 'San Marino', flag: '🇸🇲', code: 'SM', dial_code: '+378', pattern: '.... ......' },
  { name: 'Saudi Arabia', flag: '🇸🇦', code: 'SA', dial_code: '+966', pattern: '.. ...-....' },
  { name: 'Senegal', flag: '🇸🇳', code: 'SN', dial_code: '+221', pattern: '.. ... .. ..' },
  { name: 'Serbia', flag: '🇷🇸', code: 'RS', dial_code: '+381', pattern: '.. ...-....' },
  { name: 'Seychelles', flag: '🇸🇨', code: 'SC', dial_code: '+248', pattern: '...-....' },
  { name: 'Sierra Leone', flag: '🇸🇱', code: 'SL', dial_code: '+232', pattern: '.. ...-...' },
  { name: 'Singapore', flag: '🇸🇬', code: 'SG', dial_code: '+65', pattern: '....-....' },
  { name: 'Slovakia', flag: '🇸🇰', code: 'SK', dial_code: '+421', pattern: '... ... ...' },
  { name: 'Slovenia', flag: '🇸🇮', code: 'SI', dial_code: '+386', pattern: '.. ...-...' },
  { name: 'Somalia', flag: '🇸🇴', code: 'SO', dial_code: '+252', pattern: '.. ...-....' },
  { name: 'South Africa', flag: '🇿🇦', code: 'ZA', dial_code: '+27', pattern: '.. ...-....' },
  { name: 'South Korea', flag: '🇰🇷', code: 'KR', dial_code: '+82', pattern: '..-....-....' },
  { name: 'Spain', flag: '🇪🇸', code: 'ES', dial_code: '+34', pattern: '... ... ...' },
  { name: 'Sri Lanka', flag: '🇱🇰', code: 'LK', dial_code: '+94', pattern: '.. ...-....' },
  { name: 'St. Lucia', flag: '🇱🇨', code: 'LC', dial_code: '+1758', pattern: '(...) ...-....' },
  { name: 'Sudan', flag: '🇸🇩', code: 'SD', dial_code: '+249', pattern: '.. ...-....' },
  { name: 'Sweden', flag: '🇸🇪', code: 'SE', dial_code: '+46', pattern: '..-... .. ..' },
  { name: 'Switzerland', flag: '🇨🇭', code: 'CH', dial_code: '+41', pattern: '.. ... .. ..' },
  { name: 'Syria', flag: '🇸🇾', code: 'SY', dial_code: '+963', pattern: '... ...-...' },
  { name: 'Taiwan', flag: '🇹🇼', code: 'TW', dial_code: '+886', pattern: '... ...-...' },
  { name: 'Tanzania', flag: '🇹🇿', code: 'TZ', dial_code: '+255', pattern: '... ... ...' },
  { name: 'Thailand', flag: '🇹🇭', code: 'TH', dial_code: '+66', pattern: '.. ...-....' },
  { name: 'Togo', flag: '🇹🇬', code: 'TG', dial_code: '+228', pattern: '.. .. .. ..' },
  { name: 'Tonga', flag: '🇹🇴', code: 'TO', dial_code: '+676', pattern: '.....' },
  { name: 'Trinidad and Tobago', flag: '🇹🇹', code: 'TT', dial_code: '+1868', pattern: '(...) ...-....' },
  { name: 'Tunisia', flag: '🇹🇳', code: 'TN', dial_code: '+216', pattern: '.. ... ...' },
  { name: 'Turkey', flag: '🇹🇷', code: 'TR', dial_code: '+90', pattern: '... ...-....' },
  { name: 'Turkmenistan', flag: '🇹🇲', code: 'TM', dial_code: '+993', pattern: '.. ..-..-..' },
  { name: 'U.S. Virgin Islands', flag: '🇻🇮', code: 'VI', dial_code: '+1340', pattern: '(...) ...-....' },
  { name: 'Uganda', flag: '🇺🇬', code: 'UG', dial_code: '+256', pattern: '...-......' },
  { name: 'Ukraine', flag: '🇺🇦', code: 'UA', dial_code: '+380', pattern: '.. ...-..-..' },
  { name: 'United Arab Emirates', flag: '🇦🇪', code: 'AE', dial_code: '+971', pattern: '.. ...-....' },
  { name: 'United Kingdom', flag: '🇬🇧', code: 'GB', dial_code: '+44', pattern: '.... ......' },
  { name: 'United States', flag: '🇺🇸', code: 'US', dial_code: '+1', pattern: '(...) ...-....' },
  { name: 'Uruguay', flag: '🇺🇾', code: 'UY', dial_code: '+598', pattern: '... ... ...' },
  { name: 'Uzbekistan', flag: '🇺🇿', code: 'UZ', dial_code: '+998', pattern: '.. ...-..-..' },
  { name: 'Venezuela', flag: '🇻🇪', code: 'VE', dial_code: '+58', pattern: '...-.......' },
  { name: 'Vietnam', flag: '🇻🇳', code: 'VN', dial_code: '+84', pattern: '.. ...-....' },
  { name: 'Yemen', flag: '🇾🇪', code: 'YE', dial_code: '+967', pattern: '... ... ...' },
  { name: 'Zambia', flag: '🇿🇲', code: 'ZM', dial_code: '+260', pattern: '.. ...-....' },
  { name: 'Zimbabwe', flag: '🇿🇼', code: 'ZW', dial_code: '+263', pattern: '.. ...-....' },
];
