import React from 'react';
import type { Message } from '@/src/lib/types';
import { Logo } from './Logo';

// Import all the display components needed
import GeneratedImage from './GeneratedImage';
import CodeBlock from './CodeBlock';
import NewsDisplay from './NewsDisplay';
import JobListingDisplay from './JobListingDisplay';
import PracticeDisplay from './PracticeDisplay';
import StudyGuideDisplay from './StudyGuideDisplay';
import VideoDisplay from './VideoDisplay';
import MeetingReportDisplay from './MeetingReportDisplay';
import { formatText, linkifyText } from '@/src/lib/utils';

interface SharedContentViewerProps {
  message: Message;
}

const SharedContentViewer: React.FC<SharedContentViewerProps> = ({ message }) => {
    const renderContent = () => {
        // This function will render the specific content of the message
        // It's a simplified version of the logic in ChatUI
        return (
            <>
                {message.text && <div className="prose" dangerouslySetInnerHTML={{ __html: linkifyText(formatText(message.text)) }} />}
                {message.image && <GeneratedImage src={`data:${message.image.mimeType};base64,${message.image.data}`} />}
                {message.codeBlock && <CodeBlock language={message.codeBlock.language} code={message.codeBlock.code} />}
                {message.news && <NewsDisplay news={message.news} />}
                {message.job && <JobListingDisplay job={message.job} resumeContent={null} handleAnalyzeSynergy={() => {}} handleStartInterview={() => {}} handleDraftCoverLetter={() => {}} />}
                {message.practice && <PracticeDisplay practice={message.practice} />}
                {message.studyGuide && <StudyGuideDisplay studyGuide={message.studyGuide} />}
                {message.video && <VideoDisplay video={message.video} />}
                {message.meetingReport && message.text && <MeetingReportDisplay reportText={message.text} />}
            </>
        );
    };

    return (
        <div className="min-h-screen bg-[var(--bg-primary)] text-[var(--text-primary)] font-mono flex flex-col items-center p-4 sm:p-8">
            <header className="w-full max-w-4xl mb-8 flex items-center justify-between">
                <div className="flex items-center gap-3">
                    <Logo persona="Agent Zero" />
                    <h1 className="header-title">Webzero Shared Content</h1>
                </div>
                <a 
                    href={window.location.origin} 
                    className="px-4 py-2 text-sm bg-cyan-900/50 border border-cyan-700 rounded-md hover:bg-cyan-800 text-cyan-300 transition-colors"
                >
                    Open Webzero
                </a>
            </header>

            <main className="w-full max-w-4xl bg-black/30 border border-[var(--border-color)] p-6 sm:p-8 rounded-lg shadow-2xl">
                <div className="mb-4">
                    <p className="text-sm text-gray-400">
                        Shared by {message.sender === 'bot' ? 'AI Agent' : 'User'} on {new Date(message.timestamp).toLocaleString()}
                    </p>
                </div>
                <div className="prose max-w-none">
                    {renderContent()}
                </div>
            </main>

             <footer className="w-full max-w-4xl mt-8 text-center text-xs text-gray-500">
                <p>This is a read-only view of content generated by the Webzero AI interface.</p>
            </footer>
        </div>
    );
};

export default SharedContentViewer;